### ISSUE TITLE
[PE-D][Tester D] Insufficient diagrams in DG to support the implementation

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F14b-4/tp#182]
Steps to reproduce:

1. Current DG only shows the upload command diagram which may not be useful for Mac user at current release

Suggested behavior: Expect to have more diagrams to support implementation regarding birthday date & payment check

![Screenshot 2024-11-08 at 4.58.45 PM.png](https://raw.githubusercontent.com/SamsonChew/ped/main/files/cb774564-4d7e-4813-a321-1adf3ca3be7f.png)

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: SamsonChew/ped#14

**Comment by meatyturtle** [comment]
The upload command is currently functional for Windows users. You are indeed correct to say that it may not be useful for Mac users at the current release, but there are a sizeable amount of Windows users testing our product and this implementation diagram serves them. While we are apologetic that the upload feature is not supported on Mac and Linux, users are free to simply disregard this section in the developer guide instead of reporting it as a bug, to which it is not.
